# Generated by Django 3.2.5 on 2021-07-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prduct',
            new_name='product',
        ),
    ]
